language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk11

script:
  - ./gradlew build --scan -s

after_success:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
  - bash <(curl -s https://codecov.io/bash)

stages:
  - test
  - name: build
    if: branch = release

jobs:
  include:
    - stage: test
      script:
        - echo "Skip tests"
    - stage: build
      script: ./scripts/build.sh
      