language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk11

script:
  - ./gradlew build --scan -s

stages:
  - test
  - name: build
    if: branch = release

jobs:
  include:
    - stage: test
      script: ./scripts/generateJaCoCoReport.sh
    - stage: build
      script: ./scripts/build.sh
      